baseURL = 'https://nainablog.vercel.app/'
languageCode = 'en-us'
title = "ijadux2's website"
theme = "hugo-blog-awesome"
defaultContentLanguage = "en-gb"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[author]
name = "Kumar Vaibhav"
email = "kv26102009@gmail.com"

[languages.en-gb]
languageName = "English"
languageCode = "en-gb"
contentDir = "content"
weight = 1
author = "Kumar Vaibhav"

[languages.en-gb.menu]
[[languages.en-gb.menu.main]]
pageRef="/"
name = 'Home'
url = '/'
weight = 10
[[languages.en-gb.menu.main]]
pageRef="posts"
name = 'Posts'
url = '/posts/'
weight = 20
[[languages.en-gb.menu.main]]
pageRef="about"
name = 'About'
url = '/about/'
weight = 30

[languages.en-gb.params]
sitename = "ijadux2's website"
defaultColor = "dark"
description = "Open-Source Contributor"
mainSections = ['posts']
toc = true
tocOpen = false
goToTop = true
dateFormat = ""

[languages.en-gb.params.author]
avatar = "avatar.jpg"
intro = "System Programmer & Automation Expert"
name = "Kumar Vaibhav"
description = "My personal portfolio website"

[languages.en-gb.params.webmanifest]
name = "ijadux2"
short_name = "ijadux2"
start_url = "/"
theme_color = "#434648"
background_color = "#131418"
display = "standalone"

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[taxonomies]
category = "categories"
tag = "tags"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ijadux2"

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/ijadux2.bsky.social"

[[params.socialIcons]]
name = "Email"
url = "mailto:kv26102009@gmail.com"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
